language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install .
scripts:
  - pipenv run pytest --cov-report term --cov=flask_bootstrap tests/
after_success:
  - codecov